name: Deploy Frontend on Azure

on:
  workflow_dispatch:
   inputs:
       environment_name:
          description: "Environment Name"
          required: true
          default: ""
          
jobs:
  Deploy-Frontend:
    environment:
      name: ${{ github.event.inputs.environment_name }}
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Download Frontend Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-frontend.yml
          name: organizer-frontend
          branch: ${{ steps.extract_branch.outputs.branch }}
          path: ./deploy

    
      - name: Config Settings Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'deploy/assets/config/config.production.json'
        env:
          api.key: ${{ secrets.APPSERVICE_CONFIG_APIKEY }}
          api.url: ${{ secrets.APPSERVICE_FE_CONFIG_APIURL }}

      - name: Deploy Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name:    ${{ secrets.APPSERVICENAME_FE }}
          package: ./deploy
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE_FE }}
        
